# Generated by Django 4.2.7 on 2023-12-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('food_category', models.CharField(max_length=50)),
                ('expected_shelf_life', models.IntegerField()),
                ('expected_fridge_life', models.IntegerField()),
                ('expected_freezer_life', models.IntegerField()),
                ('default_storage_method', models.CharField(max_length=50)),
            ],
        ),
    ]
